# Generated by Django 4.1.6 on 2023-02-28 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapps', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='donors_in_site',
            name='phone',
            field=models.CharField(max_length=14,null=True,blank=True) ,
        ),
    ]
