# Generated by Django 4.1.6 on 2023-03-04 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapps', '0002_donors_in_site_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='donors_in_site',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='donors_in_site',
            name='slug',
            field=models.SlugField(null=True),
        ),
    ]
