# Generated by Django 4.1.6 on 2023-03-18 13:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapps', '0004_contact_us_rename_dob_donors_in_site_last_donate'),
    ]

    operations = [
        migrations.AddField(
            model_name='donors_in_site',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
