# Generated by Django 4.1.6 on 2023-03-25 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapps', '0005_donors_in_site_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donors_in_site',
            name='name',
        ),
    ]
