# Generated by Django 4.1.6 on 2023-03-25 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapps', '0006_remove_donors_in_site_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='donors_in_site',
            name='name',
            field=models.CharField(default='username', max_length=124),
        ),
    ]
