# Generated by Django 4.1.6 on 2023-03-26 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapps', '0007_donors_in_site_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donors_in_site',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
