# Generated by Django 4.1.6 on 2023-03-27 18:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Newsfeed', '0004_post_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='cmnt_likes',
            field=models.ManyToManyField(null=True, related_name='comment_likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
