# Generated by Django 4.1.6 on 2023-03-29 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Newsfeed', '0006_post_image_alter_comment_cmnt_likes_alter_post_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='comment_images'),
        ),
    ]
