# Generated by Django 4.1.6 on 2023-04-12 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Newsfeed', '0013_alter_post_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PostFile',
        ),
    ]
